package mcgill.ecse539.pos.editor;

/*Generated by MPS */

import jetbrains.mps.smodel.action.IReferentPresentationProvider;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class PresentationProviders {
  public static final IReferentPresentationProvider PRESENTATION_4s9j9m_a0a0a = ((IReferentPresentationProvider) (sourceNode, targetNode) -> SPropertyOperations.getString(targetNode, PROPS.name$hNcp));

  private static final class PROPS {
    /*package*/ static final SProperty name$hNcp = MetaAdapterFactory.getProperty(0x7d3ecb5c844f43f0L, 0x98db2b52b269987bL, 0x2c84f4c6bbf62522L, 0x2c84f4c6bbf62533L, "name");
  }
}
