package mcgill.ecse539.pos.sandbox;

/*Generated by MPS */

import java.util.Calendar;

public class BillImpl {
  private int paymentAmount;
  private boolean paymentStatus;
  private int transactionId;
  private Calendar date = new Calendar.Builder().build();
  private POSImpl.TransactionType transactionType;
  private OrderImpl order;

  public BillImpl(int paymentAmount, boolean paymentStatus, int id, int year, int month, int day, POSImpl.TransactionType transactionType, OrderImpl orderImpl) {
    this.paymentAmount = paymentAmount;
    this.paymentStatus = paymentStatus;
    this.transactionId = id;
    this.date.set(year, month, day);
    this.order = orderImpl;
  }

  public int getId() {
    return transactionId;
  }
}
