package mcgill.ecse539.pos.sandbox;

/*Generated by MPS */


public class InventoryItemImpl {
  private int quantity;
  private String name;

  public InventoryItemImpl(String name, int quantity) {
    this.quantity = quantity;
    this.name = name;
  }

  public int getQuantity() {
    return this.quantity;
  }

  public int diminishQuantity() {
    return this.quantity - 1;
  }

  public String getName() {
    return this.name;
  }

  public void setQuantity(int newQuantity) {
    this.quantity = newQuantity;
  }
}
