package mcgill.ecse539.pos.sandbox;

/*Generated by MPS */

import java.util.ArrayList;

public class MenuItemImpl {
  private int id;
  private int price;
  private String name;
  private ArrayList<InventoryItemImpl> ingredients = new ArrayList<>();

  public MenuItemImpl(int id, int price, String name, ArrayList<InventoryItemImpl> ingredients) {
    this.id = id;
    this.price = price;
    this.name = name;
    for (int i = 0; i < ingredients.size(); i++) {
      this.ingredients.add(ingredients.get(i));
    }
  }

  public int getId() {
    return id;
  }
}
