package mcgill.ecse539.pos.sandbox;

/*Generated by MPS */

import java.util.ArrayList;

public class OrderImpl {
  private String id;
  private ArrayList<OrderItemConceptImpl> orderItems = new ArrayList<OrderItemConceptImpl>();

  public OrderImpl(String id, ArrayList<OrderItemConceptImpl> orderItems) {
    this.id = id;
    for (int i = 0; i < orderItems.size(); i++) {
      this.orderItems.add(orderItems.get(i));
    }
  }

  public String getId() {
    return id;
  }
  public ArrayList<OrderItemConceptImpl> getOrderItems() {
    return this.orderItems;
  }
  public void setnewItemInOrder(OrderItemConceptImpl item) {
    orderItems.add(item);
  }

}
