package mcgill.ecse539.pos.sandbox;

/*Generated by MPS */


public class OrderItemConceptImpl {
  private int quantity;
  private MenuItemImpl menuItem;

  public OrderItemConceptImpl(int quantity, MenuItemImpl menu) {
    this.quantity = quantity;
    this.menuItem = menu;
  }

  public MenuItemImpl getItemName() {
    return menuItem;
  }
}
