package mcgill.ecse539.pos.sandbox;

/*Generated by MPS */

import java.util.HashMap;
import java.util.Scanner;

public class POSImpl {
  private HashMap<Integer, EmployeeImpl> employees = new HashMap<>();
  private HashMap<Integer, TableImpl> tables = new HashMap<>();
  private InventoryImpl inventory;

  public enum TransactionType {
    Credit(),
    Cash(),
    Debit()
  }

  public static void main(String[] args) {
    Scanner scanner = new Scanner(System.in);
    POSImpl pos = new POSImpl();

    // setup
    EmployeeImpl employee_a = new EmployeeImpl(11, "aaa");
    pos.employees.put(employee_a.getId(), employee_a);

    TableImpl table_a = new TableImpl(12);
    TableImpl table_b = new TableImpl(13);
    TableImpl table_c = new TableImpl(14);
    pos.tables.put(table_a.getNumber(), table_a);
    pos.tables.put(table_b.getNumber(), table_b);
    pos.tables.put(table_c.getNumber(), table_c);

    pos.inventory = new InventoryImpl();
    pos.inventory.createItem("posca", 10);
    pos.inventory.createItem("asofoetida", 111);
    pos.inventory.createItem("silphium", 10);
    pos.inventory.createItem("garum", 10000);
    pos.inventory.createItem("vinum", 12);
    pos.inventory.createItem("pork", 3000);

    System.out.println("POS started, input q to quit");

    String scan = scanner.nextLine();
    while (!(scan.equals("q"))) {
      scan = scanner.nextLine();
    }
  }
}
