package mcgill.ecse539.pos.sandbox;

/*Generated by MPS */


public class TableImpl {
  private int tableNumber;
  private boolean busy = false;

  public TableImpl(int tableNumber) {
    this.tableNumber = tableNumber;
  }

  public int getNumber() {
    return tableNumber;
  }

  public boolean getBusy() {
    return busy;
  }

  public void setBusy(boolean busy) {
    this.busy = busy;
  }
}
