package mcgill.ecse539.pos.sandbox;

/*Generated by MPS */


public class TableImpl {
  private int tableNumber;

  public TableImpl(int tableNumber) {
    this.tableNumber = tableNumber;
  }

  public int getNumber() {
    return tableNumber;
  }
}
